-- ============================================================================
-- Account Planning — agent Schema
-- ============================================================================
-- AI agent conversations, short-term and long-term memory, tenant/LOB/user
-- preferences, and tenant-isolated prompt template management.
-- ============================================================================

-- ============================================================================
-- 12.1 CONVERSATIONS
-- ============================================================================
-- CONCEPT
--   Every time a user opens a chat session with an AI agent in the Account
--   Planning platform, a row is created in agent.conversation.  It is the
--   top-level container that ties together the user, the optional customer
--   they are discussing, the agent type they invoked, and all messages
--   exchanged during the session.
--
--   A conversation has a clear lifecycle: it begins, work happens (messages
--   accumulate), and it ends — either successfully (completed), by the user
--   walking away (abandoned), or due to a system error (error).
--
-- AGENT TYPES
--   sales_assistant    — general sales coaching and deal guidance.
--   briefing_agent     — generates pre-meeting intelligence briefings for RMs.
--   action_planner     — creates and schedules next-best-action recommendations.
--   analytics_agent    — answers ad-hoc data questions in natural language.
--   general            — catch-all for new or uncategorised agent interactions.
--   onboarding         — guides new users through the platform setup flow.
--
-- EXAMPLE
--   A Relationship Manager (RM) is preparing for a meeting with customer
--   "Acme Corp" and opens the briefing agent:
--     tenant_id   → 'bank-tenant-uuid'
--     user_id     → 'rm-jane-uuid'
--     customer_id → 'acme-corp-uuid'
--     agent_type  → 'briefing_agent'
--     status      → 'active'          (RM is in the session)
--     metadata    → {"channel": "web", "initial_intent": "pre_meeting_brief",
--                    "device": "desktop"}
--
--   When the RM closes the chat:
--     status    → 'completed'
--     ended_at  → now()
--
-- NOTES
--   • customer_id is nullable — some agent types (e.g. onboarding, analytics)
--     are not tied to a specific customer.
--   • metadata captures session-level context: the intent, channel, and device
--     used.  It is NOT the place for message-level data (see 12.2).
--   • A single user can have many concurrent conversations (different tabs /
--     devices), each tracked as a separate row.
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.conversation (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       UUID NOT NULL REFERENCES core.tenant(id),
    user_id         UUID NOT NULL REFERENCES core.user_(id),
    customer_id     UUID REFERENCES customer.customer(id),
    agent_type      VARCHAR(50) NOT NULL
                    CHECK (agent_type IN ('sales_assistant', 'briefing_agent', 'action_planner', 'analytics_agent', 'general', 'onboarding')),
    status          VARCHAR(20) NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'completed', 'abandoned', 'error')),
    metadata        JSONB NOT NULL DEFAULT '{}',
    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at        TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE agent.conversation IS 'AI agent conversation sessions with context tracking.';
COMMENT ON COLUMN agent.conversation.metadata IS 'Session context: channel, device, initial intent, referrer';

-- ============================================================================
-- 12.2 CONVERSATION MESSAGES
-- ============================================================================
-- CONCEPT
--   agent.conversation_message stores the ordered transcript of every message
--   exchanged inside a conversation.  Each row is one discrete turn in the
--   dialogue — a user question, an assistant reply, a system instruction, or
--   a tool/function call result.
--
--   Storing the full transcript is critical for three reasons:
--     1. Context replay — the AI model needs the prior messages to generate
--        a coherent next response (the "context window").
--     2. Auditability — banks and regulated industries must be able to
--        reproduce exactly what the AI said to a user.
--     3. Debugging & fine-tuning — transcripts are the raw material for
--        evaluating agent quality and training future models.
--
-- ROLES
--   user        — text typed by the human (RM, analyst, manager).
--   assistant   — response generated by the AI model.
--   system      — invisible instruction injected at the start of a session
--                 to shape the agent's behavior (e.g. "You are a banking
--                 assistant. Never discuss competitors.").
--   tool        — result returned after the agent called an external tool
--                 (e.g. queried a database, ran a calculation).
--   function    — deprecated OpenAI naming; kept for backwards compatibility.
--
-- KEY FIELDS
--   structured_content  — used when the message carries machine-readable data
--                         rather than (or in addition to) plain text.
--                         Examples: a tool-call JSON payload, a structured
--                         briefing card, a list of action recommendations.
--   token_count         — number of LLM tokens consumed by this message.
--                         Aggregated at conversation level for cost tracking.
--   model_name          — the exact model that produced an 'assistant' message
--                         (e.g. 'gpt-4o', 'gemini-1.5-pro').  Enables A/B
--                         comparisons across model versions.
--   message_order       — 1-based sequence within the conversation.
--                         Determines the order messages are fed to the model.
--
-- EXAMPLE
--   Conversation turn for briefing_agent on Acme Corp:
--     1: role='system',    content='You are a banking RM assistant…'
--     2: role='user',      content='Give me a briefing on Acme Corp before my 3pm call.'
--     3: role='tool',      structured_content={"customer_id":"acme","revenue":12000000,…}
--     4: role='assistant', content='Here is Acme Corp's briefing: …', token_count=340
--
-- NOTES
--   • content is nullable to allow pure structured messages (e.g. tool results
--     that have no natural-language component).
--   • message_order must be enforced at application layer; gaps are allowed
--     (e.g. after a failed tool call that was retried).
--   • Do not delete messages — they are part of the audit trail.
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.conversation_message (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id           UUID NOT NULL REFERENCES core.tenant(id),
    conversation_id     UUID NOT NULL REFERENCES agent.conversation(id),
    role                VARCHAR(20) NOT NULL
                        CHECK (role IN ('user', 'assistant', 'system', 'tool', 'function')),
    content             TEXT,
    structured_content  JSONB,
    token_count         INTEGER,
    model_name          VARCHAR(100),
    message_order       INTEGER NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE agent.conversation_message IS 'Individual messages within an agent conversation.';
COMMENT ON COLUMN agent.conversation_message.structured_content IS 'For tool calls, structured API responses, parsed outputs';

-- ============================================================================
-- 12.3 SHORT-TERM MEMORY
-- ============================================================================
-- CONCEPT
--   Short-term memory is the agent's working scratchpad — ephemeral state
--   that only needs to survive for the duration of a session or a short
--   time window, after which it is automatically discarded via expires_at.
--
--   This table fills the gap between what an LLM context window can hold
--   (limited to ~128K tokens) and what the agent needs to keep consistent
--   across multiple tool calls or across pages in a multi-step workflow.
--
-- MEMORY TYPES
--   context       — variables extracted from the ongoing conversation that
--                   are referenced in later turns (e.g. the customer name
--                   the user mentioned two messages ago).
--   working       — intermediate computation results the agent is building
--                   up before delivering a final answer (e.g. partial
--                   briefing sections while the agent queries multiple tools).
--   scratch       — free-form notes the agent writes to itself to stay
--                   coherent across a multi-step plan.
--   tool_state    — the cursor / pagination token for a long-running tool
--                   call that spans multiple API pages.
--
-- EXAMPLE
--   During a 20-minute briefing session the agent stores:
--     key='active_customer_id', value='"acme-corp-uuid"',
--       memory_type='context', expires_at=now()+2h
--
--     key='briefing_sections_done', value='["financials","contacts"]',
--       memory_type='working', expires_at=now()+30m
--
--     key='crm_cursor', value='{"page":3,"token":"abc123"}',
--       memory_type='tool_state', expires_at=now()+10m
--
--   A background job (e.g. pg_cron) runs hourly:
--     DELETE FROM agent.memory_short_term WHERE expires_at < now();
--
-- NOTES
--   • session_id links memory to a specific conversation (or sub-flow)
--     without requiring a hard FK, allowing flexibility for non-conversation
--     agent workflows (e.g. background batch agents).
--   • Both user_id and customer_id are nullable — memory can be scoped
--     to a session alone (neither user nor customer locked).
--   • The (tenant_id, session_id, key) combination should be unique at the
--     application layer; the schema leaves this to app logic for flexibility.
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.memory_short_term (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       UUID NOT NULL REFERENCES core.tenant(id),
    user_id         UUID REFERENCES core.user_(id),
    customer_id     UUID REFERENCES customer.customer(id),
    session_id      UUID,
    memory_type     VARCHAR(30) NOT NULL
                    CHECK (memory_type IN ('context', 'working', 'scratch', 'tool_state')),
    key             VARCHAR(255) NOT NULL,
    value           JSONB NOT NULL,
    expires_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE agent.memory_short_term IS 'Ephemeral agent memory. Auto-cleaned by expiry. Per-session or per-user context.';

-- ============================================================================
-- 12.4 LONG-TERM MEMORY
-- ============================================================================
-- CONCEPT
--   Long-term memory is the agent's persistent knowledge base about the
--   entities it deals with — customers, products, employees, org units, and
--   tenants.  Unlike short-term memory it survives beyond a single session
--   and accumulates over time, making the agent progressively smarter and
--   more personalised with each interaction.
--
--   Think of it as the agent's CRM notepad, but automatically maintained:
--   every conversation that reveals something meaningful about a customer
--   (their communication preferences, a risk indicator, a key relationship)
--   produces a new row here.
--
-- MEMORY CATEGORIES
--   preference           — how the entity prefers to be communicated with.
--                          e.g. "Acme CFO prefers email over phone; no calls
--                          before 10:00 am."
--   key_fact             — stable, important facts confirmed about the entity.
--                          e.g. "Acme Corp's fiscal year ends March 31."
--   relationship_note    — qualitative notes on the relationship dynamic.
--                          e.g. "Decision-maker is the CTO, not the CFO."
--   behavioral_pattern   — observed patterns over multiple interactions.
--                          e.g. "Acme consistently delays renewals by 60 days."
--   communication_style  — tone and formality preferences.
--                          e.g. "CEO prefers bullet-point briefs, not prose."
--   risk_indicator       — early warning signals observed by the agent.
--                          e.g. "3 consecutive missed follow-up responses."
--   opportunity          — growth or upsell signals.
--                          e.g. "Expressed interest in FX hedging products."
--
-- KEY FIELDS
--   confidence      — how certain the agent is that this memory is accurate,
--                     on a 0–1 scale.  Starts at 0.80 for an inferred memory,
--                     rises to 1.00 if the user explicitly confirms it, and
--                     may be decayed by a scheduled job if not re-referenced
--                     in recent sessions.
--   source          — how the memory was captured:
--                     'conversation'   — directly stated by a user in chat.
--                     'observation'    — inferred by the agent from behavior.
--                     'inference'      — model-generated hypothesis, lower conf.
--                     'user_confirmed' — a human explicitly marked it as true.
--                     'core_system'    — imported from a trusted source (CRM).
--   last_accessed_at — updated every time the agent retrieves this memory
--                      during a session.  Used by relevance-ranking queries
--                      to surface the most recently useful memories first.
--
-- EXAMPLE
--   After a call debrief session, the agent creates two memories:
--
--     entity_type     = 'customer'
--     entity_id       = 'acme-corp-uuid'
--     memory_category = 'risk_indicator'
--     content         = 'CFO mentioned budget freeze for Q3 — no new contracts.'
--     confidence      = 0.90
--     source          = 'conversation'
--     source_conversation_id → the debrief session UUID
--
--     memory_category = 'communication_style'
--     content         = 'Prefers WhatsApp messages over email for quick updates.'
--     confidence      = 0.85
--     source          = 'user_confirmed'
--
-- NOTES
--   • is_active = false soft-deletes a memory without losing the history
--     (e.g. when a 'risk_indicator' is resolved).
--   • The agent memory retrieval query typically filters:
--     entity_type = 'customer', entity_id = $1, is_active = true
--     ORDER BY confidence DESC, last_accessed_at DESC LIMIT 20
--   • confidence decay should be implemented as a scheduled job, not a trigger,
--     to avoid write amplification on every SELECT.
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.memory_long_term (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id               UUID NOT NULL REFERENCES core.tenant(id),
    entity_type             VARCHAR(30) NOT NULL
                            CHECK (entity_type IN ('customer', 'product', 'employee', 'org_unit', 'tenant')),
    entity_id               UUID NOT NULL,
    memory_category         VARCHAR(50) NOT NULL
                            CHECK (memory_category IN ('preference', 'key_fact', 'relationship_note', 'behavioral_pattern', 'communication_style', 'risk_indicator', 'opportunity')),
    content                 TEXT NOT NULL,
    structured_data         JSONB,
    confidence              DECIMAL(3,2) DEFAULT 0.80
                            CHECK (confidence >= 0 AND confidence <= 1),
    source                  VARCHAR(50) NOT NULL DEFAULT 'observation'
                            CHECK (source IN ('conversation', 'observation', 'inference', 'user_confirmed', 'core_system')),
    source_conversation_id  UUID REFERENCES agent.conversation(id),
    is_active               BOOLEAN NOT NULL DEFAULT true,
    last_accessed_at        TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE agent.memory_long_term IS 'Persistent agent memory about entities. Key facts, preferences, behavioral patterns.';
COMMENT ON COLUMN agent.memory_long_term.confidence IS 'Agent confidence in this memory (0.00–1.00). Decays over time if not reconfirmed.';
COMMENT ON COLUMN agent.memory_long_term.last_accessed_at IS 'For relevance scoring — less recently accessed memories may be deprioritized';

-- ============================================================================
-- 12.5 PREFERENCES (Tenant/LOB/User Scoped)
-- ============================================================================
-- CONCEPT
--   agent.preference is a hierarchical key-value store that controls how the
--   agent behaves at different organisational levels.  More specific settings
--   override less specific ones, allowing platform-wide defaults to be
--   customised per tenant, per line of business, per region, or per individual
--   user — without needing columns for every possible setting.
--
--   Override precedence (most specific wins):
--     user  >  team  >  region  >  lob  >  tenant
--
-- SCOPE LEVELS
--   tenant    — global default for all users of this tenant.
--               scope_entity_id = tenant.id
--   lob       — override for a specific line of business (e.g. "Retail Banking").
--               scope_entity_id = org_unit.id (of type 'lob')
--   region    — override for a geographic region (e.g. "EMEA").
--               scope_entity_id = org_unit.id (of type 'region')
--   team      — override for a specific sales team.
--               scope_entity_id = org_unit.id (of type 'team')
--   user      — personal preference set by the individual user.
--               scope_entity_id = core.user_.id
--
-- EXAMPLE — language preference
--   The bank operates in 30 countries.  The default language for agent
--   responses is English (tenant-level).  The Spain team overrides it:
--
--     scope='tenant', scope_entity_id=bank-tenant,
--       preference_key='agent.response_language', preference_value='"en"'
--
--     scope='region', scope_entity_id=spain-region-unit,
--       preference_key='agent.response_language', preference_value='"es"'
--
--     scope='user', scope_entity_id=carlos-user-uuid,
--       preference_key='agent.response_language', preference_value='"ca"'
--       → Carlos's agent always responds in Catalan.
--
-- EXAMPLE — briefing verbosity
--   scope='lob', scope_entity_id=retail-banking-lob,
--     preference_key='briefing_agent.verbosity', preference_value='"concise"'
--
--   scope='user', scope_entity_id=senior-rm-uuid,
--     preference_key='briefing_agent.verbosity', preference_value='"detailed"'
--   → This RM always gets detailed briefings regardless of LOB default.
--
-- NOTES
--   • preference_value is JSONB, not TEXT, so it can store booleans, numbers,
--     arrays, or objects as well as simple strings.
--   • The UNIQUE constraint (tenant_id, scope, scope_entity_id, preference_key)
--     ensures only one value per key per scope entity — upsert on conflict.
--   • is_active = false lets admins disable a preference without deleting it,
--     falling through to the next level in the hierarchy.
--   • The application layer is responsible for the override resolution logic;
--     the DB stores all levels flat.
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.preference (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id           UUID NOT NULL REFERENCES core.tenant(id),
    scope               VARCHAR(30) NOT NULL
                        CHECK (scope IN ('tenant', 'lob', 'region', 'team', 'user')),
    scope_entity_id     UUID NOT NULL,
    preference_key      VARCHAR(255) NOT NULL,
    preference_value    JSONB NOT NULL,
    is_active           BOOLEAN NOT NULL DEFAULT true,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, scope, scope_entity_id, preference_key)
);

COMMENT ON TABLE agent.preference IS 'Hierarchical preference store: tenant → LOB → region → team → user. More specific overrides general.';

-- ============================================================================
-- 12.6 PROMPT TEMPLATES (Tenant-Isolated)
-- ============================================================================
-- CONCEPT
--   A prompt template is the reusable, versioned instruction set that tells
--   an AI agent how to behave for a specific task.  Instead of embedding raw
--   prompts in application code (fragile, hard to audit), this table makes
--   prompts a first-class managed artifact: they can be authored, reviewed,
--   tested, versioned, and approved through a workflow — then served at
--   runtime by code that never needs to be redeployed.
--
--   Key design decisions:
--     • Tenant-isolated — every tenant manages its own prompt variations.
--       A conservative bank can use a formally worded template while a fintech
--       uses casual language, both on the same platform.
--     • Versioned — templates are never overwritten in-place.  A new version
--       is created, tested, and promoted to is_current = true while the old
--       version remains available for rollback.
--     • Schema-validated — input_schema and output_schema define what variables
--       a template expects and what structured output it should produce,
--       enabling the application to validate calls before they hit the LLM.
--
-- STATUS FLOW
--   draft  →  testing  →  active   (promoted to is_current = true)
--                      ↘  deprecated  (replaced by a newer version)
--
-- KEY FIELDS
--   code             — stable machine identifier for this template family
--                      (e.g. 'briefing_agent_v2', 'action_planner_main').
--                      The application references prompts by code, not UUID,
--                      so it is immune to UUID changes across environments.
--   template_content — the actual prompt text with {{variable}} placeholders.
--                      Example:
--                        "You are a banking assistant for {{bank_name}}.
--                         Generate a meeting briefing for customer {{customer_name}}
--                         covering: financials, recent interactions, open actions."
--   input_schema     — JSON Schema declaring required/optional variables.
--                      Example: {"required":["bank_name","customer_name"],
--                                "optional":["tone","max_length"]}
--   output_schema    — expected structured output.
--                      Example: {"sections":["summary","financials","risks"],
--                                "format":"markdown"}
--   model_config     — LLM hyperparameters for this template.
--                      Example: {"model":"gpt-4o","temperature":0.3,"max_tokens":2000}
--   is_current       — true on exactly one row per (tenant_id, code) pair at
--                      any time.  Managed by the promotion workflow.
--
-- EXAMPLE LIFECYCLE
--   1. Prompt engineer AUTHORS a new briefing template:
--      code='briefing_main', version=3, status='draft', is_current=false
--   2. QA tests it against 10 sample customers:
--      status='testing'
--   3. Manager approves it (approved_by=manager-uuid):
--      status='active', is_current=true
--      → previous version 2: is_current=false, status='deprecated'
--   4. If version 3 regresses, roll back by setting version=2 is_current=true.
--
-- NOTES
--   • (tenant_id, code, version) is UNIQUE — the same code can exist at
--     multiple versions for the same tenant, but never two rows at the same
--     version.
--   • Only one row per (tenant_id, code) should have is_current=true;
--     enforce this at application layer via a transaction that flips the old
--     current row before setting the new one.
--   • model_config at the template level is the default; individual agent
--     invocations may override specific fields (e.g. temperature) at runtime.
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.prompt_template (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id           UUID NOT NULL REFERENCES core.tenant(id),
    code                VARCHAR(100) NOT NULL,
    name                VARCHAR(255) NOT NULL,
    description         TEXT,
    agent_type          VARCHAR(50) NOT NULL,
    template_content    TEXT NOT NULL,
    input_schema        JSONB,
    output_schema       JSONB,
    model_config        JSONB NOT NULL DEFAULT '{}',
    version             INTEGER NOT NULL DEFAULT 1,
    is_current          BOOLEAN NOT NULL DEFAULT false,
    status              VARCHAR(20) NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft', 'active', 'deprecated', 'testing')),
    created_by          UUID REFERENCES core.user_(id),
    approved_by         UUID REFERENCES core.user_(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, code, version)
);

COMMENT ON TABLE agent.prompt_template IS 'Tenant-isolated prompt templates managed by app admins. Each tenant has independent versions.';
COMMENT ON COLUMN agent.prompt_template.template_content IS 'Prompt template with {{variable}} placeholders';
COMMENT ON COLUMN agent.prompt_template.model_config IS '{"model": "gpt-4", "temperature": 0.3, "max_tokens": 2000}';
COMMENT ON COLUMN agent.prompt_template.input_schema IS 'JSON Schema defining required template variables';
COMMENT ON COLUMN agent.prompt_template.output_schema IS 'Expected structured output schema for parsing';
