-- ============================================================================
-- Account Planning — notification Schema
-- ============================================================================
-- In-database notification system with optional external provider integration.
-- Supports email, SMS, push, in-app, and webhook channels.
--
-- ── WHO RECEIVES NOTIFICATIONS? ─────────────────────────────────────────────
--   Notifications in this schema target INTERNAL platform users — the bank's
--   own employees — NOT end-customers.  Typical recipients are:
--
--   • Relationship Managers (RMs) — alerted about upcoming actions, overdue
--     tasks, or AI-generated briefings before a customer meeting.
--   • Team Managers / Supervisors — notified when an RM's action is
--     escalated, an SLA is breached, or a performance target is at risk.
--   • Analysts — informed when a scheduled report is ready or an anomaly is
--     detected in a customer's financial data.
--   • System Administrators — receive platform-level alerts (maintenance
--     windows, integration failures, quota warnings).
--
--   Customer-facing communications (e.g. marketing emails sent TO the bank's
--   corporate customers) are outside the scope of this schema. Those are
--   handled by the CRM/marketing stack, not the Account Planning platform.
--
-- ── WHAT TRIGGERS A NOTIFICATION? ───────────────────────────────────────────
--   Notifications are generated by four distinct subsystems:
--
--   1. Action Engine (07_action.sql)
--      — Fires when an action is due, overdue, or escalated.
--        e.g. "Your 'Q2 Review Call' with Acme Corp is due tomorrow."
--        e.g. "Escalation: John's action has been overdue for 3 days."
--
--   2. AI Agent Layer (12_agent.sql)
--      — Fires when the agent completes an async task or detects an insight.
--        e.g. "Your pre-meeting briefing for Acme Corp is ready."
--        e.g. "AI Alert: Acme Corp's revenue trend shows a 15% decline."
--
--   3. Performance & Target Engine (06_performance.sql)
--      — Fires when a KPI crosses a threshold or a reporting period closes.
--        e.g. "Your Q2 revenue target is at 42% with 30 days remaining."
--        e.g. "Monthly performance report for April is now available."
--
--   4. Integration / Sync Layer (11_integration.sql)
--      — Fires when an external data sync fails or produces anomalous data.
--        e.g. "CRM sync failed: 3 customer records could not be imported."
--
--   Each notification row stores trigger_type, trigger_entity_type, and
--   trigger_entity_id so the origin of every message is fully traceable.
--
-- ── HOW ARE NOTIFICATIONS PLANNED AND SCHEDULED? ────────────────────────────
--   Notifications can be immediate or deferred:
--
--   • Immediate — scheduled_at IS NULL.  The worker picks these up as soon as
--     they are inserted (status='pending') and dispatches them within seconds.
--     Used for escalations, urgent alerts, and real-time AI insights.
--
--   • Scheduled — scheduled_at IS NOT NULL.  The notification worker runs a
--     periodic sweep (e.g. every minute) and picks up rows where
--     status='pending' AND scheduled_at <= now().  Used for digest emails,
--     morning briefings, and report deliveries timed to business hours.
--     Example: an RM's briefing is generated at 06:00 but scheduled_at is set
--     to 07:30 so it arrives just before their 09:00 meeting.
--
--   • Quiet-hours enforcement — even immediate notifications are held if the
--     recipient has a quiet_hours window configured in notification.preference
--     and the current time falls within it.  The worker re-queues held rows
--     with a new scheduled_at = start-of-next-allowed-window.
--     Exception: priority='urgent' always bypasses quiet hours.
--
-- ── HOW IS THE RIGHT CHANNEL SELECTED? ──────────────────────────────────────
--   Channel routing happens at dispatch time using three inputs:
--     1. notification.preference — the user's per-category, per-channel
--        opt-in/opt-out setting (is_enabled).
--     2. notification.channel    — the tenant's active provider for each
--        channel_type (is_active=true).  If a provider is down, the router
--        skips it and tries the next available channel of the same type.
--     3. notification.priority   — 'urgent' may force SMS/push even if the
--        user prefers email for that category.
--
-- ── SCHEMA OVERVIEW ──────────────────────────────────────────────────────────
--   13.1  channel     — tenant-level registry of delivery providers.
--   13.2  template    — versioned, localised message blueprints.
--   13.3  notification — individual dispatched messages and their lifecycle.
--   13.4  preference  — per-user opt-in/opt-out and quiet-hours settings.
-- ============================================================================

-- ============================================================================
-- 13.1 NOTIFICATION CHANNELS
-- ============================================================================
-- CONCEPT
--   notification.channel is the registry of delivery conduits available to a
--   tenant.  Before any notification can be sent, the tenant must have at
--   least one active channel configured.  A channel is a combination of:
--     • channel_type  — the medium (email, SMS, push notification, in-app
--                       banner, or outbound webhook).
--     • provider      — the external or internal service that physically
--                       delivers the message (SendGrid for email, Twilio for
--                       SMS, Firebase for mobile push, etc.).
--
--   Each tenant may configure multiple channels of the same type (e.g., a
--   primary SendGrid channel and a fallback SES channel for email), and the
--   application selects the best available active channel at send time.
--
-- PROVIDERS
--   internal         — no external call is made; message is stored in the DB
--                      for in-app rendering only.
--   sendgrid         — transactional email via SendGrid API.
--   ses              — Amazon Simple Email Service (AWS).
--   mailgun          — transactional email via Mailgun.
--   twilio           — SMS delivery via Twilio REST API.
--   firebase         — mobile push notifications via Firebase Cloud Messaging.
--   custom_webhook   — POST a JSON payload to a tenant-defined HTTPS endpoint.
--
-- KEY FIELDS
--   config       — ENCRYPTED JSONB blob containing provider credentials and
--                  settings (API keys, sender addresses, webhook URLs).
--                  Never exposed to end-users; only readable by the
--                  notification service itself.
--   rate_limit   — optional throttle applied before calling the provider to
--                  prevent abuse and cost overruns.  The application checks
--                  this value and delays or drops messages that exceed the
--                  threshold.
--
-- EXAMPLE — bank tenant configures three channels:
--   1. EMAIL via SendGrid:
--      channel_type='email', provider='sendgrid',
--      config={"api_key": "SG.xxx", "from": "noreply@bank.com"},
--      rate_limit={"max_per_hour": 500, "max_per_day": 5000, "max_per_user_hour": 20}
--
--   2. SMS via Twilio:
--      channel_type='sms', provider='twilio',
--      config={"account_sid": "ACxxx", "auth_token": "...", "from": "+15551234567"},
--      rate_limit={"max_per_hour": 100, "max_per_day": 1000, "max_per_user_hour": 5}
--
--   3. In-App (internal, no external calls):
--      channel_type='in_app', provider='internal', config={}
--
-- NOTES
--   • A channel marked is_active=false is skipped by the notification router
--     without deleting tenant configuration — useful for temporarily disabling
--     a provider during an outage.
--   • config must be encrypted at rest using the platform's field-level
--     encryption key before INSERT; the application layer is responsible.
-- ============================================================================

CREATE TABLE IF NOT EXISTS notification.channel (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       UUID NOT NULL REFERENCES core.tenant(id),
    channel_type    VARCHAR(30) NOT NULL
                    CHECK (channel_type IN ('email', 'sms', 'push', 'in_app', 'webhook')),
    provider        VARCHAR(50) NOT NULL DEFAULT 'internal'
                    CHECK (provider IN ('internal', 'sendgrid', 'twilio', 'firebase', 'custom_webhook', 'ses', 'mailgun')),
    config          JSONB NOT NULL DEFAULT '{}',
    is_active       BOOLEAN NOT NULL DEFAULT true,
    rate_limit      JSONB NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE notification.channel IS 'Per-tenant notification channel configuration. Supports internal and external providers.';
COMMENT ON COLUMN notification.channel.config IS 'ENCRYPTED — API keys, endpoints, sender addresses, provider-specific config';
COMMENT ON COLUMN notification.channel.rate_limit IS '{"max_per_hour": 100, "max_per_day": 1000, "max_per_user_hour": 10}';

-- ============================================================================
-- 13.2 NOTIFICATION TEMPLATES
-- ============================================================================
-- CONCEPT
--   notification.template stores the reusable, localised message blueprints
--   used to generate consistent notifications across the system.  Rather than
--   hardcoding message text in application code, every notification type is
--   defined here — enabling non-technical admins to update wording, translate
--   messages, or version content without a code deployment.
--
--   Each template is scoped to a:
--     • tenant — organisations author their own branded messages.
--     • channel_type — email templates have a subject + body; SMS/push have
--       only a body; in-app may use rich HTML.
--     • locale — the same logical template (code) can exist in multiple
--       languages (e.g. 'tr', 'en', 'de').
--     • version — templates are versioned so rollback is always possible.
--       is_current=true marks the live version for a given
--       (tenant, code, channel_type, locale) combination.
--
-- TEMPLATE SYNTAX
--   body_template and subject_template use {{variable}} placeholder syntax.
--   The application resolves these at send time by merging a data context
--   validated against variables_schema.
--   Example body:
--     "Dear {{user_name}}, your action '{{action_title}}' is due in
--      {{hours_remaining}} hours. Click here to view: {{action_url}}"
--
-- KEY FIELDS
--   code             — stable machine identifier shared across versions and
--                      locales (e.g. 'action_due_reminder', 'briefing_ready').
--                      The application backend references templates by code.
--   variables_schema — JSON Schema that declares which placeholder variables
--                      are required/optional, enabling pre-send validation.
--
-- EXAMPLE — action due reminder template set up for two locales:
--   Row 1:
--     tenant_id=bank-uuid, code='action_due_reminder',
--     channel_type='email', locale='en', version=2, is_current=true,
--     subject_template='Action Due: {{action_title}}',
--     body_template='Hi {{user_name}}, your action is due in {{hours_remaining}}h.',
--     variables_schema={"required": ["user_name", "action_title", "hours_remaining"]}
--
--   Row 2:
--     code='action_due_reminder', channel_type='email', locale='tr',
--     version=2, is_current=true,
--     subject_template='Görev Hatırlatması: {{action_title}}',
--     body_template='Merhaba {{user_name}}, göreviniz {{hours_remaining}} saat içinde son bulacak.'
--
-- NOTES
--   • The UNIQUE constraint (tenant_id, code, channel_type, locale, version)
--     prevents duplicate entries; use ON CONFLICT DO UPDATE to bump version.
--   • is_current=false rows are kept for audit and rollback — never DELETE.
--   • subject_template is nullable because SMS and in-app notifications have
--     no subject line concept.
-- ============================================================================

CREATE TABLE IF NOT EXISTS notification.template (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id           UUID NOT NULL REFERENCES core.tenant(id),
    code                VARCHAR(100) NOT NULL,
    channel_type        VARCHAR(30) NOT NULL,
    subject_template    TEXT,
    body_template       TEXT NOT NULL,
    variables_schema    JSONB NOT NULL DEFAULT '{}',
    locale              VARCHAR(10) NOT NULL DEFAULT 'tr',
    version             INTEGER NOT NULL DEFAULT 1,
    is_current          BOOLEAN NOT NULL DEFAULT true,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, code, channel_type, locale, version)
);

COMMENT ON TABLE notification.template IS 'Notification templates per channel and locale. Supports {{variable}} placeholders.';
COMMENT ON COLUMN notification.template.subject_template IS 'For email/push — subject line template. Supports i18n keys.';

-- ============================================================================
-- 13.3 NOTIFICATIONS
-- ============================================================================
-- CONCEPT
--   notification.notification is the central ledger that records every
--   individual notification dispatched (or scheduled) by the platform.  Each
--   row represents one notification sent to one recipient via one channel —
--   from the moment it is created as 'pending' all the way through delivery
--   confirmation (or failure) and the recipient reading or dismissing it.
--
--   This table serves two purposes:
--     1. Operational delivery queue — the notification worker polls rows
--        with status='pending' or status='queued', attempts delivery, and
--        updates the row with the result (sent_at, delivered_at, failed_at).
--     2. Audit trail — provides a full history of what was communicated to
--        whom, when, and why — critical for regulatory audits and debugging.
--
-- STATUS LIFECYCLE
--   pending   → queued   → sent   → delivered  (happy path)
--                                 → failed      (provider error, retry_count exhausted)
--   delivered             → read
--   read / delivered      → dismissed
--
-- TRIGGER CONCEPT
--   trigger_type, trigger_entity_type, and trigger_entity_id record the
--   business event that caused this notification to be generated — providing
--   traceable causality between platform events and user communications.
--
-- KEY FIELDS
--   template_id          — optional FK to the template used; NULL if the
--                           notification was generated with a one-off body.
--   priority             — low/normal/high/urgent controls queue ordering
--                           and whether quiet-hours are respected (urgent
--                           always bypasses quiet-hours).
--   scheduled_at         — for deferred notifications (e.g. a reminder
--                           scheduled for 08:00 next business day).  The
--                           worker only picks up a row when now() ≥ scheduled_at.
--   retry_count          — incremented on each failed delivery attempt;
--                           the worker gives up after a configured max (e.g. 3).
--   metadata             — arbitrary key-value context about the notification
--                           (e.g. deep-link URL, CTA button label, image URL).
--
-- EXAMPLE — escalation notification for an overdue action:
--   tenant_id             = bank-uuid
--   recipient_user_id     = manager-uuid
--   channel_type          = 'email'
--   template_id           → 'action_escalation' template UUID
--   subject               = 'Escalation: "Quarterly Review" is 3 days overdue'
--   body                  = 'Hello Anna, the action assigned to John is overdue…'
--   priority              = 'high'
--   trigger_type          = 'action_escalation'
--   trigger_entity_type   = 'action.action_instance'
--   trigger_entity_id     → the overdue action_instance UUID
--   status                = 'delivered' → read_at = 2026-04-15T09:12:00Z
--
-- EXAMPLE — scheduled briefing-ready notification:
--   trigger_type = 'briefing_ready'
--   scheduled_at = 2026-04-19T07:30:00Z   (sent before the 09:00 meeting)
--   priority     = 'normal'
--   channel_type = 'push'
--   body         = 'Your briefing for Acme Corp is ready. Tap to view.'
--
-- NOTES
--   • Do not hard-delete rows; set status='dismissed' and retain for audit.
--   • For in-app notifications, the frontend polls or subscribes (WebSocket/
--     SSE) for rows where status IN ('sent','delivered') AND channel_type='in_app'.
--   • retry_count should be checked before each re-attempt; stop at max_retries
--     defined in the channel's config.
-- ============================================================================

CREATE TABLE IF NOT EXISTS notification.notification (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id               UUID NOT NULL REFERENCES core.tenant(id),
    template_id             UUID REFERENCES notification.template(id),
    recipient_user_id       UUID NOT NULL REFERENCES core.user_(id),
    channel_type            VARCHAR(30) NOT NULL,
    subject                 TEXT,
    body                    TEXT NOT NULL,
    priority                VARCHAR(20) NOT NULL DEFAULT 'normal'
                            CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    status                  VARCHAR(20) NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'queued', 'sent', 'delivered', 'failed', 'read', 'dismissed')),
    trigger_type            VARCHAR(50),
    trigger_entity_type     VARCHAR(100),
    trigger_entity_id       UUID,
    scheduled_at            TIMESTAMPTZ,
    sent_at                 TIMESTAMPTZ,
    delivered_at            TIMESTAMPTZ,
    read_at                 TIMESTAMPTZ,
    failed_at               TIMESTAMPTZ,
    error_message           TEXT,
    retry_count             INTEGER NOT NULL DEFAULT 0,
    metadata                JSONB NOT NULL DEFAULT '{}',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE notification.notification IS 'Individual notification instances with full delivery lifecycle tracking.';
COMMENT ON COLUMN notification.notification.trigger_type IS 'Action escalation, SLA breach, briefing ready, system alert, etc.';

-- ============================================================================
-- 13.4 NOTIFICATION PREFERENCES
-- ============================================================================
-- CONCEPT
--   notification.preference gives each user fine-grained control over which
--   types of notifications they receive and on which channels.  Rather than
--   a single on/off global mute, preferences are segmented by both
--   channel_type (email, SMS, in-app…) and notification_category (action
--   alerts, briefings, AI insights…), so a user can, for example, receive
--   action escalations via push but opt out of marketing emails entirely.
--
--   The notification router checks this table before dispatching any message.
--   If is_enabled=false for the matching (user, channel_type, category)
--   combination, the notification is silently suppressed — no row is created
--   in notification.notification, preserving clean delivery metrics.
--
-- CATEGORIES
--   action_alerts   — reminders and escalations for assigned actions.
--   briefings       — AI-generated pre-meeting intelligence briefings.
--   system          — platform alerts: maintenance windows, errors, upgrades.
--   escalations     — manager-level alerts when actions or targets are overdue.
--   reports         — scheduled performance and analytics report deliveries.
--   ai_insights     — proactive recommendations or anomaly alerts from the agent.
--   marketing       — product announcements, feature spotlights (optional).
--
-- KEY FIELDS
--   quiet_hours     — a time window during which non-urgent notifications
--                     are held and not delivered, even if is_enabled=true.
--                     The notification router compares the current time in the
--                     user's timezone against this window before dispatch.
--                     Only priority='urgent' bypasses quiet_hours.
--
-- EXAMPLE — RM "Jane" configures her preferences:
--   Row 1:
--     user_id=jane-uuid, channel_type='email',
--     notification_category='action_alerts', is_enabled=true,
--     quiet_hours={"start": "22:00", "end": "08:00", "timezone": "Europe/Istanbul"}
--     → Jane gets action alert emails, but not between 10pm and 8am Istanbul time.
--
--   Row 2:
--     user_id=jane-uuid, channel_type='sms',
--     notification_category='briefings', is_enabled=false
--     → Jane never receives briefing notifications via SMS (she prefers in-app).
--
--   Row 3:
--     user_id=jane-uuid, channel_type='in_app',
--     notification_category='ai_insights', is_enabled=true, quiet_hours=NULL
--     → In-app AI insight notifications are always on, no time restriction.
--
-- NOTES
--   • The UNIQUE constraint (tenant_id, user_id, channel_type, notification_category)
--     ensures exactly one preference row per combination; use ON CONFLICT DO UPDATE
--     to handle user preference changes.
--   • If no preference row exists for a (user, channel, category) combination,
--     the application should default to is_enabled=true (opt-out model).
--   • quiet_hours=NULL means no time restriction — notifications may be
--     delivered at any hour for that channel/category pair.
--   • 'urgent' priority notifications (e.g. system outage alerts) MUST bypass
--     quiet_hours at the application layer regardless of this setting.
-- ============================================================================

CREATE TABLE IF NOT EXISTS notification.preference (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id               UUID NOT NULL REFERENCES core.tenant(id),
    user_id                 UUID NOT NULL REFERENCES core.user_(id),
    channel_type            VARCHAR(30) NOT NULL,
    notification_category   VARCHAR(50) NOT NULL
                            CHECK (notification_category IN ('action_alerts', 'briefings', 'system', 'escalations', 'reports', 'ai_insights', 'marketing')),
    is_enabled              BOOLEAN NOT NULL DEFAULT true,
    quiet_hours             JSONB,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, user_id, channel_type, notification_category)
);

COMMENT ON TABLE notification.preference IS 'User notification preferences per channel and category. Supports quiet hours.';
COMMENT ON COLUMN notification.preference.quiet_hours IS '{"start": "22:00", "end": "08:00", "timezone": "Europe/Istanbul"}';
