-- ============================================================================
-- Account Planning — document Schema
-- ============================================================================
-- Document metadata management. Files stored externally (S3/blob).
-- Supports versioning, entity linking, and access audit logging.
--
-- ── WHAT IS THE document SCHEMA? ────────────────────────────────────────────
--   The document schema stores metadata about files that are attached to, or
--   generated by, the Account Planning platform.  Physical file content is
--   NEVER stored in the database — it lives in an external blob store (Amazon
--   S3, Azure Blob, GCS, or MinIO for on-prem deployments).  The database
--   holds a lightweight metadata record: where the file is, who uploaded it,
--   its size, checksum, encryption status, and the business entities it is
--   associated with.
--
-- ── WHAT KINDS OF DOCUMENTS ARE STORED? ─────────────────────────────────────
--   • Contracts & signed forms — legal agreements uploaded by Relationship
--     Managers (RMs) to confirm a deal or customer consent.
--   • Meeting notes & call reports — recordings or typed summaries attached
--     to a customer interaction or action.
--   • AI-generated briefings — PDF exports of the pre-meeting intelligence
--     brief produced by the AI agent layer (12_agent.sql).
--   • Performance reports — monthly/quarterly KPI reports exported from the
--     analytics layer and archived here for stakeholder reference.
--   • Evidence & photos — supporting documents attached to compliance actions
--     (e.g. site visit photos, KYC scan uploads).
--   • Data exports — CSV/Excel files generated during data-sync jobs
--     (11_integration.sql) or customer data requests (GDPR exports).
--
-- ── WHO GENERATES DOCUMENTS? ────────────────────────────────────────────────
--   Documents enter the system through three paths:
--
--   1. Manual upload by internal users (RMs, analysts, admins)
--      — A user uploads a file via the web or mobile app.
--      — The application uploads the binary to blob storage, then INSERTs a
--        row in document.document with storage_path, checksum, and
--        uploaded_by.
--
--   2. AI Agent / Report Generator (automatic)
--      — The AI agent (12_agent.sql) or the report engine generates a binary
--        (PDF/CSV), writes it to blob storage, then creates a document row
--        and links it to the triggering entity (e.g. a conversation or a
--        reporting period) via document.document_link.
--
--   3. Integration Layer (11_integration.sql)
--      — Inbound sync jobs may receive files from external CRM/ERP systems
--        and store them here for downstream processing or compliance archiving.
--
-- ── WHO CONSUMES DOCUMENTS? ─────────────────────────────────────────────────
--   • Web & mobile frontend — the UI queries document.document_link to list
--     files attached to a customer, action, or conversation, then generates
--     a short-lived pre-signed URL from the blob store for secure download.
--   • Compliance / audit teams — query document.document_access_log to
--     demonstrate that sensitive files are accessed only by authorised users.
--   • AI Agent — reads attached documents (contract text, meeting notes) as
--     additional context when generating briefing content.
--   • Data retention service — periodically checks document.document for
--     rows that have exceeded the tenant's retention policy and triggers
--     blob-storage deletion followed by setting is_active=false / deleted_at.
--
-- ── SECURITY MODEL ───────────────────────────────────────────────────────────
--   • Every row has tenant_id so Row-Level Security (RLS) policies ensure
--     cross-tenant isolation — a user can only see documents belonging to
--     their own tenant.
--   • Sensitive files (contracts, GDPR exports) are stored with
--     is_encrypted=true and the encryption key reference (not the key itself)
--     is held in encryption_key_ref (pointing to the platform KMS).
--   • The application layer generates short-lived (e.g. 15-minute) pre-signed
--     URLs from the blob store at download time; the storage_path is never
--     exposed directly to browser clients.
--   • Every view, download, print, or share action is written to
--     document.document_access_log for audit purposes.
--
-- ── SCHEMA OVERVIEW ──────────────────────────────────────────────────────────
--   14.1  document             — master metadata record for every file.
--   14.2  document_version     — full history of file revisions.
--   14.3  document_link        — polymorphic association to any entity.
--   14.4  document_access_log  — fine-grained access audit trail.
-- ============================================================================

-- ============================================================================
-- 14.1 DOCUMENTS
-- ============================================================================
-- CONCEPT
--   document.document is the master record for every file managed by the
--   platform.  It does NOT store binary data — instead it stores enough
--   metadata for the application to:
--     a) locate the file in the external blob store (storage_backend +
--        storage_bucket + storage_path),
--     b) verify file integrity (checksum_sha256),
--     c) render a human-readable name in the UI (display_name, mime_type),
--     d) enforce access control (tenant_id, uploaded_by, is_encrypted).
--
--   When a user uploads a file the backend workflow is:
--     1. Upload binary to blob store → receive the storage_path (object key).
--     2. INSERT a row here with all metadata.
--     3. INSERT a row in document_version (version 1).
--     4. INSERT one or more rows in document_link to associate the file with
--        the relevant business entity (customer, action, conversation, etc.).
--
-- SOFT DELETE
--   is_active=false + deleted_at timestamp is used instead of hard DELETE to
--   preserve audit history.  The data retention service sets these fields once
--   a file's retention window expires and then submits a blob-store deletion
--   job.  The file is inaccessible via the UI as soon as is_active=false even
--   if the blob still exists pending the async deletion.
--
-- KEY FIELDS
--   storage_backend  — controls which SDK the application uses to interact
--                      with the file ('s3' → AWS SDK, 'azure_blob' → Azure
--                      SDK, 'gcs' → GCP SDK, 'local'/'minio' → S3-compatible).
--   storage_path     — the object key or file path within the bucket/container.
--                      Not a public URL — the application generates pre-signed
--                      URLs on-demand at access time.
--   checksum_sha256  — computed by the application before upload and verified
--                      after download to detect bit-rot or tampering.
--   encryption_key_ref — if is_encrypted=true, this contains the KMS key alias
--                      or ARN used to encrypt the blob (e.g. 'arn:aws:kms:...')
--                      so the application knows which key to request for
--                      decryption.  The actual key is never stored here.
--
-- EXAMPLE — an RM uploads a signed contract PDF for Acme Corp:
--   filename          = 'acme_corp_contract_2026_signed.pdf'
--   display_name      = 'Acme Corp — 2026 Framework Agreement (Signed)'
--   mime_type         = 'application/pdf'
--   size_bytes        = 2457600  (≈ 2.4 MB)
--   storage_backend   = 's3'
--   storage_bucket    = 'accountplanning-docs-prod'
--   storage_path      = 'tenants/bank-uuid/contracts/acme_corp_2026_signed.pdf'
--   checksum_sha256   = 'e3b0c44298fc1c149afbf4c8996fb924...'
--   is_encrypted      = true
--   encryption_key_ref = 'arn:aws:kms:eu-west-1:123:key/mrk-xxx'
--   uploaded_by       → RM user UUID
--
-- EXAMPLE — AI agent exports a briefing PDF for a 09:00 meeting:
--   filename          = 'briefing_acme_corp_20260419.pdf'
--   display_name      = 'Briefing: Acme Corp — 2026-04-19'
--   mime_type         = 'application/pdf'
--   storage_backend   = 's3'
--   uploaded_by       → system-service-account UUID
--
-- NOTES
--   • mime_type should be set by the application (not trusted from the
--     client) by running MIME detection on the binary after upload.
--   • size_bytes must be verified against the blob-store reported size post-
--     upload to catch upload truncation errors.
-- ============================================================================

CREATE TABLE IF NOT EXISTS document.document (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id           UUID NOT NULL REFERENCES core.tenant(id),
    filename            VARCHAR(500) NOT NULL,
    display_name        VARCHAR(255) NOT NULL,
    mime_type           VARCHAR(100) NOT NULL,
    size_bytes          BIGINT NOT NULL,
    storage_backend     VARCHAR(30) NOT NULL DEFAULT 's3'
                        CHECK (storage_backend IN ('s3', 'azure_blob', 'gcs', 'local', 'minio')),
    storage_path        VARCHAR(1000) NOT NULL,
    storage_bucket      VARCHAR(255),
    checksum_sha256     VARCHAR(64) NOT NULL,
    is_encrypted        BOOLEAN NOT NULL DEFAULT false,
    encryption_key_ref  VARCHAR(255),
    uploaded_by         UUID NOT NULL REFERENCES core.user_(id),
    is_active           BOOLEAN NOT NULL DEFAULT true,
    deleted_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE document.document IS 'Document metadata. Physical files stored in external blob storage.';
COMMENT ON COLUMN document.document.storage_path IS 'Path/key in the storage backend (e.g., S3 object key)';
COMMENT ON COLUMN document.document.encryption_key_ref IS 'Reference to encryption key in KMS (not the key itself)';

-- ============================================================================
-- 14.2 DOCUMENT VERSIONS
-- ============================================================================
-- CONCEPT
--   document.document_version tracks the complete revision history of a file.
--   Every time a user uploads a new version of an existing document (e.g. a
--   revised contract, an updated report), a new row is inserted here with an
--   incremented version_number, while the parent document.document row keeps
--   its identity.  The application always presents the highest version_number
--   as the "current" file, but older versions remain accessible for audit and
--   rollback.
--
--   Version 1 is created automatically when the parent document row is first
--   inserted.  Subsequent versions are created each time the user clicks
--   "Upload new version" in the UI.
--
--   Each version has its own storage_path — the new binary is stored as a
--   separate object in blob storage (not overwriting the previous).  This
--   ensures that older versions can always be retrieved even if the tenant's
--   blob lifecycle policy eventually archives them to cold storage.
--
-- WHEN IS THIS TABLE USED?
--   • When an RM re-uploads a signed contract after amendments.
--   • When a report is regenerated with corrected data.
--   • When the AI agent produces a revised briefing for the same meeting.
--   • By compliance tools to show the exact document state at any point in time.
--
-- KEY FIELDS
--   version_number  — monotonically increasing integer within a document.
--                     The UNIQUE (document_id, version_number) constraint
--                     prevents concurrent uploads from creating duplicate
--                     version numbers; optimistic locking at the application
--                     layer (e.g. SELECT MAX(version_number) FOR UPDATE) is
--                     recommended before INSERT.
--   change_summary  — optional free-text note from the uploader describing
--                     what changed in this version (e.g. "Clause 4 revised
--                     per legal review 2026-04-19").
--
-- EXAMPLE — contract goes through two revisions:
--   Version 1 (initial upload):
--     document_id=acme-contract-uuid, version_number=1,
--     storage_path='tenants/.../contracts/acme_v1.pdf',
--     size_bytes=2457600, change_summary=NULL
--
--   Version 2 (after legal review):
--     document_id=acme-contract-uuid, version_number=2,
--     storage_path='tenants/.../contracts/acme_v2.pdf',
--     size_bytes=2523136, change_summary='Clause 4 revised — penalty cap updated'
--
-- NOTES
--   • The parent document.document row is NOT updated when a new version is
--     created; the "current" version is resolved by MAX(version_number).
--   • Alternatively, the application can store a current_version_id FK on the
--     document row for O(1) lookup — consider adding this as a later optimisation
--     if version resolution becomes a hot query path.
--   • Never hard-delete version rows; versions must be preserved for
--     regulatory and rollback purposes.
-- ============================================================================

CREATE TABLE IF NOT EXISTS document.document_version (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id           UUID NOT NULL REFERENCES core.tenant(id),
    document_id         UUID NOT NULL REFERENCES document.document(id),
    version_number      INTEGER NOT NULL,
    storage_path        VARCHAR(1000) NOT NULL,
    size_bytes          BIGINT NOT NULL,
    checksum_sha256     VARCHAR(64) NOT NULL,
    change_summary      TEXT,
    uploaded_by         UUID NOT NULL REFERENCES core.user_(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (document_id, version_number)
);

COMMENT ON TABLE document.document_version IS 'Document version history. Each upload creates a new version.';

-- ============================================================================
-- 14.3 DOCUMENT LINKS (Entity Association)
-- ============================================================================
-- CONCEPT
--   document.document_link is a polymorphic join table that associates a
--   document with any entity in the system — without requiring a dedicated FK
--   column on every entity table.  Instead of adding document_id to the
--   customer, action, or conversation table, a single link row declares:
--     "document X is attached to entity Y of type Z, for purpose W."
--
--   This design has two key advantages:
--     1. A single document can be linked to multiple entities simultaneously.
--        Example: the same signed NDA is linked to both the customer record
--        and the specific action that triggered the signing.
--     2. New entity types can be supported in the link table's CHECK constraint
--        without migrating any other table structure.
--
-- HOW IS THIS TABLE USED?
--   • Frontend "Documents" tab — when an RM opens a customer profile, the UI
--     queries document_link WHERE entity_type='customer' AND entity_id=<customer_uuid>
--     to list all attached files.
--   • Action completion evidence — when an RM marks an action as done, they
--     upload a file and a link row is created with entity_type='action' and
--     link_type='evidence'.
--   • AI agent context injection — at briefing-generation time, the agent
--     queries all documents linked to the relevant customer (entity_type=
--     'customer') and conversation ('conversation') to include as context.
--   • Consent & compliance — GDPR consent documents are linked to a
--     customer_consent record (entity_type='consent', link_type='signed_form').
--
-- ENTITY TYPES
--   customer        — a bank customer account (customer.customer).
--   action          — a task/action instance (action.action_instance).
--   product         — a financial product (product.product).
--   conversation    — an AI agent conversation session (agent.conversation).
--   change_request  — a config change request (config.change_request).
--   employee        — an internal user/employee (core.user_).
--   org_unit        — an organisational unit (core.org_unit).
--   consent         — a customer consent record (customer.customer_consent).
--
-- LINK TYPES
--   attachment      — generic file attachment with no specific business role.
--   evidence        — proof of completion or compliance for an action.
--   contract        — a legal agreement between the bank and a counterparty.
--   meeting_notes   — written summary or recording of a meeting.
--   signed_form     — a form signed by the customer or an internal approver.
--   report          — a scheduled or ad-hoc analytical report.
--   photo           — a site visit or KYC photograph.
--   other           — fallback for any type not covered above.
--
-- EXAMPLE — RM uploads a signed framework agreement for Acme Corp:
--   document_id   → acme-contract-uuid
--   entity_type   = 'customer'
--   entity_id     → acme-corp-customer-uuid
--   link_type     = 'contract'
--   description   = 'Signed 2026 Framework Agreement — valid until 2027-12-31'
--   created_by    → RM user UUID
--
-- EXAMPLE — same contract is also linked to the action that required it:
--   document_id   → acme-contract-uuid
--   entity_type   = 'action'
--   entity_id     → sign-framework-agreement-action-uuid
--   link_type     = 'evidence'
--   description   = 'Signed contract submitted as evidence of action completion'
--
-- NOTES
--   • The UNIQUE (document_id, entity_type, entity_id) constraint means one
--     document can only be linked once per entity.  To link the same document
--     as both 'contract' and 'evidence' on the same entity, use two separate
--     rows by removing this constraint — evaluate based on your use case.
--   • entity_id is a plain UUID without a FK constraint because the target
--     table varies per entity_type.  The application is responsible for
--     validating that entity_id refers to a real row in the correct table
--     before inserting a link record.
-- ============================================================================

CREATE TABLE IF NOT EXISTS document.document_link (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       UUID NOT NULL REFERENCES core.tenant(id),
    document_id     UUID NOT NULL REFERENCES document.document(id),
    entity_type     VARCHAR(100) NOT NULL
                    CHECK (entity_type IN ('customer', 'action', 'product', 'conversation', 'change_request', 'employee', 'org_unit', 'consent')),
    entity_id       UUID NOT NULL,
    link_type       VARCHAR(50) NOT NULL
                    CHECK (link_type IN ('attachment', 'evidence', 'contract', 'meeting_notes', 'signed_form', 'report', 'photo', 'other')),
    description     TEXT,
    created_by      UUID NOT NULL REFERENCES core.user_(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (document_id, entity_type, entity_id)
);

COMMENT ON TABLE document.document_link IS 'Polymorphic link between documents and any entity in the system.';

-- ============================================================================
-- 14.4 DOCUMENT ACCESS LOG
-- ============================================================================
-- CONCEPT
--   document.document_access_log is an append-only audit trail that records
--   every interaction a user has with a document beyond simply listing it.
--   Specifically, it captures:
--     • view   — the user opened the document preview in the UI.
--     • download — the user triggered a file download (a pre-signed URL was
--                  generated and delivered to the client).
--     • print  — the user used the in-app print function.
--     • share  — the user generated a share link or forwarded the document
--                to an external party.
--
--   This log is written by the application backend at the moment the relevant
--   action is performed — NOT by a database trigger so that the ip_address and
--   contextual metadata can be captured at the HTTP request layer.
--
-- WHY IS THIS TABLE NEEDED?
--   Regulated financial institutions must demonstrate that sensitive documents
--   (contracts, KYC scans, personal data exports) were accessed only by
--   authorised personnel and only within the scope of legitimate business
--   activities.  This table enables:
--     • Regulatory audit responses — produce a timestamped log of every user
--       who viewed or downloaded a specific contract.
--     • Incident investigation — identify who accessed a sensitive document
--       in the hours leading up to a suspected data leak.
--     • Compliance reporting — show that PII-containing exports were downloaded
--       only by the data owner's assigned RM and the compliance officer.
--     • Usage analytics — identify which documents are most frequently accessed
--       to inform archiving or caching strategies.
--
-- WHO WRITES TO THIS TABLE?
--   The backend API layer writes a row here whenever:
--     • A pre-signed download URL is generated (access_type='download').
--     • A document preview endpoint is called (access_type='view').
--     • A print job is initiated via the API (access_type='print').
--     • A share-link generation endpoint is called (access_type='share').
--   The table is NEVER written to by direct user action — only via controlled
--   server-side code paths that first verify authorisation.
--
-- WHO READS FROM THIS TABLE?
--   • Compliance officers — via an admin dashboard, filtered by document_id
--     or user_id over a date range.
--   • Security team — during incident response, querying by ip_address or
--     user_id to reconstruct access patterns.
--   • Automated retention/audit reports — scheduled queries that summarise
--     access events for regulatory submission.
--
-- KEY FIELDS
--   ip_address  — the client IP captured from the HTTP request.  Stored in
--                 VARCHAR(45) to accommodate both IPv4 (max 15 chars) and
--                 IPv6 (max 39 chars) addresses.  Treat as PII in GDPR
--                 contexts — apply the tenant's data retention policy.
--   occurred_at — the server timestamp at the moment the access event was
--                 processed (not the time the pre-signed URL was subsequently
--                 used, which cannot be captured here).
--
-- EXAMPLE — RM downloads a contract PDF:
--   document_id   → acme-contract-uuid
--   user_id       → RM jane-uuid
--   access_type   = 'download'
--   ip_address    = '10.0.4.22'
--   occurred_at   = '2026-04-19T09:14:32Z'
--
-- EXAMPLE — compliance officer views a GDPR data export:
--   document_id   → gdpr-export-uuid
--   user_id       → compliance-officer-uuid
--   access_type   = 'view'
--   ip_address    = '10.0.1.5'
--   occurred_at   = '2026-04-19T14:55:00Z'
--
-- NOTES
--   • This table is append-only — rows must never be updated or deleted during
--     the document's retention period.  Hard-delete only when the parent
--     document itself is purged and the retention policy explicitly permits it.
--   • Index on (document_id, occurred_at) and (user_id, occurred_at) to
--     support the most common audit query patterns efficiently.
--   • Consider partitioning by month (RANGE on occurred_at) if the platform
--     manages millions of documents and access events accumulate rapidly.
-- ============================================================================

CREATE TABLE IF NOT EXISTS document.document_access_log (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       UUID NOT NULL REFERENCES core.tenant(id),
    document_id     UUID NOT NULL REFERENCES document.document(id),
    user_id         UUID NOT NULL REFERENCES core.user_(id),
    access_type     VARCHAR(20) NOT NULL
                    CHECK (access_type IN ('view', 'download', 'print', 'share')),
    ip_address      VARCHAR(45),
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE document.document_access_log IS 'Audit trail for document access events.';
